# ğŸ“„ .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
issue_templates:
  - name: ê¸°ëŠ¥ ì¶”ê°€/ì‘ì—… í…œí”Œë¦¿
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ ì¶”ê°€ë‚˜ ë‚´ë¶€ ì‘ì—…ì„ ìœ„í•œ ì´ìŠˆ í…œí”Œë¦¿ì…ë‹ˆë‹¤.
    file: ISSUE_TEMPLATE.md
